before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y librdf0 
script: bundle exec rspec --format documentation spec/integration/ruby_engine_spec.rb
language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - rbx-1.3.3
  - rbx-2
  - jruby-18mode
  - jruby-19mode
cache: bundler
